version: "3"
services:
  postgresql:
    image: postgres
    container_name: db_service
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
  redis:
    image: redis
    ports:
      - "6379:6379"

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "80:80"
volumes:
  db_data:
    driver: local
