# Generated by Django 4.2.5 on 2023-09-13 14:55

from django.db import migrations, models
import django.db.models.deletion
import restaurant.utils.upload_to


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("api_key", models.CharField(max_length=36, unique=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("client", "client"), ("kitchen", "kitchen")],
                        max_length=7,
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printers",
                        to="restaurant.point",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "client"), ("kitchen", "kitchen")],
                        max_length=7,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("rendered", "rendered"),
                            ("printed", "printed"),
                        ],
                        default="new",
                        max_length=8,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=restaurant.utils.upload_to.pdf_path,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "printer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="restaurant.printer",
                    ),
                ),
            ],
        ),
    ]
