# Generated by Django 4.2.5 on 2023-09-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("rendered", "rendered"),
                    ("printed", "printed"),
                ],
                default="new",
                max_length=8,
            ),
        ),
    ]
